#ifndef BATTLE_TYPES_H
#define BATTLE_TYPES_H


#define SINGLE_WILD 0x0
#define DOUBLE_WILD 0x1
#define TRIPLE_WILD 0x2
#define HORDE_WILD 0x3
#define SINGLE_TRAINER 0x4
#define DOUBLE_TRAINER 0x5
#define DOUBLE_TWO_AI 0x6
#define TRIPLE_TRAINER 0x7
#define TRIPLE_FOUR_AI 0x8
#define TRIPLE_FIVE_AI 0x9
#define HORDE_TRAINER 0xA

#endif /* GET_ATTRIBUTE_H */
